#
# Makefile for Phoenix-RTOS pc-ata driver
#
# Copyright 2018, 2019 Phoenix Systems
#

$(PREFIX_PROG)test_scanf: $(PREFIX_O)stdio/test_scanf.o
	$(LINK)


$(PREFIX_PROG)test_str2num: $(PREFIX_O)stdio/test_str2num.o
	$(LINK)


all: $(PREFIX_PROG_STRIPPED)test_scanf $(PREFIX_PROG_STRIPPED)test_str2num
