$(eval $(call add_test, test-fail-output-1))
$(eval $(call add_test, test-fail-output-2))
$(eval $(call add_test, test-fail-exception))

$(eval $(call add_unity_test, test-fail-unity))
$(eval $(call add_unity_test, test-fail-unity-exc))

SAMPLE_TESTS += test-fail-output-1 test-fail-output-2 test-fail-exception test-fail-unity test-fail-unity-exc
