/*
 * Phoenix-RTOS
 *
 * POSIX.1-2017 standard library functions tests
 * HEADER:
 *    - <syslog.h>
 * TESTED:
 *    - openlog()
 *
 * Copyright 2026 Phoenix Systems
 * Author: Lukasz Kruszynski
 *
 * This file is part of Phoenix-RTOS.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#include <syslog.h>
#include <string.h>

#include "unity_fixture.h"

#define ALL_PRIORITIES_MASK \
	(LOG_MASK(LOG_EMERG) | LOG_MASK(LOG_ALERT) | LOG_MASK(LOG_CRIT) | \
	LOG_MASK(LOG_ERR) | LOG_MASK(LOG_WARNING) | LOG_MASK(LOG_NOTICE) | \
	LOG_MASK(LOG_INFO) | LOG_MASK(LOG_DEBUG))

#define OPENLOG_TEST_IDENT "openlog-test"


TEST_GROUP(syslog_openlog);


TEST_SETUP(syslog_openlog)
{
	closelog();
	setlogmask(ALL_PRIORITIES_MASK);
}


TEST_TEAR_DOWN(syslog_openlog)
{
	setlogmask(ALL_PRIORITIES_MASK);
	closelog();
}


TEST(syslog_openlog, openlog_with_ident)
{
	/* "The ident argument is a string that is prepended to every message" */
	openlog(OPENLOG_TEST_IDENT, 0, LOG_USER);

	/* Should not crash when logging after openlog with ident */
	syslog(LOG_INFO, "message with ident");
}


TEST(syslog_openlog, openlog_null_ident)
{
	/* NULL ident should be handled gracefully */
	openlog(NULL, 0, LOG_USER);

	syslog(LOG_INFO, "message with NULL ident");
}


TEST(syslog_openlog, openlog_empty_ident)
{
	/* Empty string ident */
	openlog("", 0, LOG_USER);

	syslog(LOG_INFO, "message with empty ident");
}


TEST(syslog_openlog, openlog_log_pid_option)
{
	/* "LOG_PID: Log the process ID with each message" */
	openlog(OPENLOG_TEST_IDENT, LOG_PID, LOG_USER);

	syslog(LOG_INFO, "message with PID");
}


TEST(syslog_openlog, openlog_log_cons_option)
{
	/* "LOG_CONS: Write messages to the system console if they cannot be
	 *  sent to the logging facility" */
	openlog(OPENLOG_TEST_IDENT, LOG_CONS, LOG_USER);

	syslog(LOG_INFO, "message with CONS option");
}


TEST(syslog_openlog, openlog_log_ndelay_option)
{
	/* "LOG_NDELAY: Open the connection to the logging facility immediately" */
	openlog(OPENLOG_TEST_IDENT, LOG_NDELAY, LOG_USER);

	syslog(LOG_INFO, "message with NDELAY");
}


TEST(syslog_openlog, openlog_log_odelay_option)
{
	/* "LOG_ODELAY: Delay open until syslog() is called" */
	openlog(OPENLOG_TEST_IDENT, LOG_ODELAY, LOG_USER);

	syslog(LOG_INFO, "message with ODELAY");
}


TEST(syslog_openlog, openlog_log_nowait_option)
{
	/* "LOG_NOWAIT: Do not wait for child processes" */
	openlog(OPENLOG_TEST_IDENT, LOG_NOWAIT, LOG_USER);

	syslog(LOG_INFO, "message with NOWAIT");
}


TEST(syslog_openlog, openlog_combined_options)
{
	/* Multiple options OR'd together */
	openlog(OPENLOG_TEST_IDENT, LOG_PID | LOG_NDELAY | LOG_NOWAIT, LOG_USER);

	syslog(LOG_ERR, "combined options %d", 42);
}


TEST(syslog_openlog, openlog_facility_log_local0_through_local7)
{
	/* "The facility argument encodes a default facility to be assigned
	 *  to all messages that do not have an explicit facility already encoded" */
	openlog(OPENLOG_TEST_IDENT, LOG_NDELAY, LOG_LOCAL0);
	syslog(LOG_ERR, "local0");
	closelog();

	openlog(OPENLOG_TEST_IDENT, LOG_NDELAY, LOG_LOCAL1);
	syslog(LOG_ERR, "local1");
	closelog();

	openlog(OPENLOG_TEST_IDENT, LOG_NDELAY, LOG_LOCAL2);
	syslog(LOG_ERR, "local2");
	closelog();

	openlog(OPENLOG_TEST_IDENT, LOG_NDELAY, LOG_LOCAL3);
	syslog(LOG_ERR, "local3");
	closelog();

	openlog(OPENLOG_TEST_IDENT, LOG_NDELAY, LOG_LOCAL4);
	syslog(LOG_ERR, "local4");
	closelog();

	openlog(OPENLOG_TEST_IDENT, LOG_NDELAY, LOG_LOCAL5);
	syslog(LOG_ERR, "local5");
	closelog();

	openlog(OPENLOG_TEST_IDENT, LOG_NDELAY, LOG_LOCAL6);
	syslog(LOG_ERR, "local6");
	closelog();

	openlog(OPENLOG_TEST_IDENT, LOG_NDELAY, LOG_LOCAL7);
	syslog(LOG_ERR, "local7");
}


TEST(syslog_openlog, openlog_facility_log_user)
{
	/* "LOG_USER: Messages generated by arbitrary processes.
	 *  This is the default facility identifier if none is specified." */
	openlog(OPENLOG_TEST_IDENT, LOG_NDELAY, LOG_USER);

	syslog(LOG_NOTICE, "LOG_USER facility");
}


TEST(syslog_openlog, openlog_called_multiple_times)
{
	/* Calling openlog multiple times should update attributes */
	openlog("first-ident", LOG_PID, LOG_LOCAL0);
	syslog(LOG_INFO, "first config");

	openlog("second-ident", LOG_NDELAY, LOG_LOCAL1);
	syslog(LOG_INFO, "second config");
}


TEST(syslog_openlog, openlog_closelog_cycle)
{
	/* closelog() "shall close any open file descriptors allocated by
	 *  previous calls to openlog() or syslog()" */
	openlog(OPENLOG_TEST_IDENT, LOG_NDELAY, LOG_USER);
	syslog(LOG_INFO, "before close");
	closelog();

	/* Logging after closelog should still work (re-opens implicitly) */
	syslog(LOG_INFO, "after close");
}


TEST(syslog_openlog, openlog_setlogmask_persists_across_openlog)
{
	/* setlogmask should persist even after openlog is called again */
	setlogmask(LOG_MASK(LOG_ERR));

	openlog("new-ident", LOG_NDELAY, LOG_LOCAL0);

#ifdef __phoenix__
	TEST_IGNORE_MESSAGE("#1647 issue");
#else
	int mask = setlogmask(0);
	TEST_ASSERT_EQUAL_INT(LOG_MASK(LOG_ERR), mask);
#endif
}


TEST_GROUP_RUNNER(syslog_openlog)
{
	RUN_TEST_CASE(syslog_openlog, openlog_with_ident);
	RUN_TEST_CASE(syslog_openlog, openlog_null_ident);
	RUN_TEST_CASE(syslog_openlog, openlog_empty_ident);
	RUN_TEST_CASE(syslog_openlog, openlog_log_pid_option);
	RUN_TEST_CASE(syslog_openlog, openlog_log_cons_option);
	RUN_TEST_CASE(syslog_openlog, openlog_log_ndelay_option);
	RUN_TEST_CASE(syslog_openlog, openlog_log_odelay_option);
	RUN_TEST_CASE(syslog_openlog, openlog_log_nowait_option);
	RUN_TEST_CASE(syslog_openlog, openlog_combined_options);
	RUN_TEST_CASE(syslog_openlog, openlog_facility_log_local0_through_local7);
	RUN_TEST_CASE(syslog_openlog, openlog_facility_log_user);
	RUN_TEST_CASE(syslog_openlog, openlog_called_multiple_times);
	RUN_TEST_CASE(syslog_openlog, openlog_closelog_cycle);
	RUN_TEST_CASE(syslog_openlog, openlog_setlogmask_persists_across_openlog);
}
