#
# Makefile for libphoenix tests
#
# Copyright 2020 Phoenix Systems
#
# %LICENSE%
#

$(PREFIX_PROG)test_disk: $(PREFIX_O)disk/test_disk.o
	$(LINK)

all: $(addprefix $(PREFIX_PROG_STRIPPED), test_disk)
