#
# Makefile for libcache tests
#
# Copyright 2022 Phoenix Systems
#
# %LICENSE%
#

NAME := test-libcache
LOCAL_SRCS := test_libcache.c libcache_utils.c
DEP_LIBS := unity libcache

include $(binary.mk)
