# vim:sw=2:ts=2
name: ci

# on events
on:
  push:
    branches:
      - master
      - 'feature/*'
  pull_request:
    branches:
      - master
      - 'feature/*'

jobs:
  call-ci:
    uses: phoenix-rtos/phoenix-rtos-project/.github/workflows/ci-submodule.yml@wmlynik/coremark_pro_tests_tmp
    secrets: inherit
  call-ci2:
    uses: phoenix-rtos/phoenix-rtos-project/.github/workflows/ci-submodule.yml@wmlynik/coremark_pro_tests_tmp
    secrets: inherit
  call-ci3:
    uses: phoenix-rtos/phoenix-rtos-project/.github/workflows/ci-submodule.yml@wmlynik/coremark_pro_tests_tmp
    secrets: inherit
  call-ci4:
    uses: phoenix-rtos/phoenix-rtos-project/.github/workflows/ci-submodule.yml@wmlynik/coremark_pro_tests_tmp
    secrets: inherit
  call-ci5:
    uses: phoenix-rtos/phoenix-rtos-project/.github/workflows/ci-submodule.yml@wmlynik/coremark_pro_tests_tmp
    secrets: inherit
