# vim:sw=2:ts=2
name: ci

# on events
on:
  push:
    branches:
      - master
      - 'feature/*'
  pull_request:
    branches:
      - master
      - 'feature/*'

env:
  LONG_TEST: "y"

jobs:
  call-ci:
    uses: phoenix-rtos/phoenix-rtos-project/.github/workflows/ci-submodule.yml@wmlynik/coremark_pro_tests
    with:
      build_params: all test project image
    secrets: inherit
